plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5' apply false
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.joeun'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

allprojects {
    group = 'com.joeun'
    version = '0.0.1-SNAPSHOT'
    sourceCompatibility = '17'
}

subprojects {
    apply plugin: "java"
    apply plugin: 'java-library'
    apply plugin: "io.spring.dependency-management"
//    apply plugin: "org.springframework.boot"

    repositories {
        mavenCentral()
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.5"
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    dependencies {
        // Lombok
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
    }
}
