plugins {
    id 'java'
}

group = 'com.joeun'
version = '0.0.1-SNAPSHOT'

bootJar {enabled = false}
jar {enabled = true}

repositories {
    mavenCentral()
}

dependencies {
    api project(':daeyo-domain:domain-service')

    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter'
    // Google Firebase Admin
    implementation 'com.google.firebase:firebase-admin:9.2.0'
    // AWS
    implementation platform("io.awspring.cloud:spring-cloud-aws-dependencies:3.2.1")
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-s3'
    implementation 'io.awspring.cloud:spring-cloud-aws-starter-secrets-manager'


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}