spring:
  cloud:
    aws:
      s3:
        region: ${AWS_REGION:ap-northeast-2}

      secretsmanager:
        region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket:
        name: daeyeohaeyoung1
    stack:
      auto: false